INSERT INTO
  us_state (state_name, postal_abbr, fips_code, last_update)
VALUES
  ('Alabama', 'AL', '01', CURRENT_TIMESTAMP),
  ('Nebraska', 'NE', '31', CURRENT_TIMESTAMP),
  ('Alaska', 'AK', '02', CURRENT_TIMESTAMP),
  ('Nevada', 'NV', '32', CURRENT_TIMESTAMP),
  ('Arizona', 'AZ', '04', CURRENT_TIMESTAMP),
  ('New Hampshire', 'NH', '33', CURRENT_TIMESTAMP),
  ('Arkansas', 'AR', '05', CURRENT_TIMESTAMP),
  ('New Jersey', 'NJ', '34', CURRENT_TIMESTAMP),
  ('California', 'CA', '06', CURRENT_TIMESTAMP),
  ('New Mexico', 'NM', '35', CURRENT_TIMESTAMP),
  ('Colorado', 'CO', '08', CURRENT_TIMESTAMP),
  ('New York', 'NY', '36', CURRENT_TIMESTAMP),
  ('Connecticut', 'CT', '09', CURRENT_TIMESTAMP),
  ('North Carolina', 'NC', '37', CURRENT_TIMESTAMP),
  ('Delaware', 'DE', '10', CURRENT_TIMESTAMP),
  ('North Dakota', 'ND', '38', CURRENT_TIMESTAMP),
  (
    'District of Columbia',
    'DC',
    '11',
    CURRENT_TIMESTAMP
  ),
  ('Ohio', 'OH', '39', CURRENT_TIMESTAMP),
  ('Florida', 'FL', '12', CURRENT_TIMESTAMP),
  ('Oklahoma', 'OK', '40', CURRENT_TIMESTAMP),
  ('Georgia', 'GA', '13', CURRENT_TIMESTAMP),
  ('Oregon', 'OR', '41', CURRENT_TIMESTAMP),
  ('Hawaii', 'HI', '15', CURRENT_TIMESTAMP),
  ('Pennsylvania', 'PA', '42', CURRENT_TIMESTAMP),
  ('Idaho', 'ID', '16', CURRENT_TIMESTAMP),
  ('Puerto Rico', 'PR', '72', CURRENT_TIMESTAMP),
  ('Illinois', 'IL', '17', CURRENT_TIMESTAMP),
  ('Rhode Island', 'RI', '44', CURRENT_TIMESTAMP),
  ('Indiana', 'IN', '18', CURRENT_TIMESTAMP),
  ('South Carolina', 'SC', '45', CURRENT_TIMESTAMP),
  ('Iowa', 'IA', '19', CURRENT_TIMESTAMP),
  ('South Dakota', 'SD', '46', CURRENT_TIMESTAMP),
  ('Kansas', 'KS', '20', CURRENT_TIMESTAMP),
  ('Tennessee', 'TN', '47', CURRENT_TIMESTAMP),
  ('Kentucky', 'KY', '21', CURRENT_TIMESTAMP),
  ('Texas', 'TX', '48', CURRENT_TIMESTAMP),
  ('Louisiana', 'LA', '22', CURRENT_TIMESTAMP),
  ('Utah', 'UT', '49', CURRENT_TIMESTAMP),
  ('Maine', 'ME', '23', CURRENT_TIMESTAMP),
  ('Vermont', 'VT', '50', CURRENT_TIMESTAMP),
  ('Maryland', 'MD', '24', CURRENT_TIMESTAMP),
  ('Virginia', 'VA', '51', CURRENT_TIMESTAMP),
  ('Massachusetts', 'MA', '25', CURRENT_TIMESTAMP),
  ('Virgin Islands', 'VI', '78', CURRENT_TIMESTAMP),
  ('Michigan', 'MI', '26', CURRENT_TIMESTAMP),
  ('Washington', 'WA', '53', CURRENT_TIMESTAMP),
  ('Minnesota', 'MN', '27', CURRENT_TIMESTAMP),
  ('West Virginia', 'WV', '54', CURRENT_TIMESTAMP),
  ('Mississippi', 'MS', '28', CURRENT_TIMESTAMP),
  ('Wisconsin', 'WI', '55', CURRENT_TIMESTAMP),
  ('Missouri', 'MO', '29', CURRENT_TIMESTAMP),
  ('Wyoming', 'WY', '56', CURRENT_TIMESTAMP),
  ('Montana', 'MT', '30', CURRENT_TIMESTAMP) RETURNING state_id,
  state_name,
  postal_abbr,
  fips_code,
  last_update;